"""Illustrate the endpoint ordering and the cyclic-reduction re-order.

Companion figures to ordering_fill, on the same endpoint-coupled
matrix (B = 2 scenarios, N = 8 stages).  Stage variables are
labeled x_t^i (stage t of scenario i); the shared root node is the
stage x_0, so each tail holds x_N^i ... x_1^i and x_1^i is the only
tail block coupled to x_0.  Two variable layouts are drawn,
one PDF each, and in both the top row uses plain chain-order prefixes
(zero fill) while the bottom row re-orders each prefix by SOCU's
batched cyclic-reduction elimination -- the order the GPU solver
actually eliminates in (O(log T) depth instead of O(T)).  The price of
the parallel order is visible as red fill-in: reduction fill between
the surviving blocks of each level inside every prefix, and connector
fill in the endpoint rows restricted to the O(log T) ancestor path of
the last prefix block.  The root columns keep exactly the matrix's own
B * n_b * n_r coupling entries in every panel.

- ``endpoint_parallel[_T8].pdf`` (T = 10 by default) -- the
  in-place endpoint
  layout the solver's storage actually uses: each tail stays
  contiguous with its own root-coupled endpoint stage kept at its end,

      [ prefix_1 e_1 | prefix_2 e_2 | ... | prefix_B e_B | root ];

- ``endpoint_ordering_noseparation[_T10].pdf`` -- no separation: the
  permutation runs over all N stages of each tail (chronological,
  reversed, and cyclic-reduction rows).

The boundary-group layout ([ prefix_1 | ... | prefix_B | e_1 ... e_B |
root ]) remains available through render_figure(..., "grouped", ...)
but is not generated by default.

Usage::

    python -m src.endpoint_tree.concept.ordering_idea

Writes both PDFs into experiments/endpoint_tree/figures/.
"""

import os
from pathlib import Path

import numpy as np
import scipy.sparse as sp

os.environ.setdefault("MPLBACKEND", "Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from matplotlib.patches import Patch

from src.endpoint_tree import EndpointTreeShape
from tests.endpoint_tree.problems import generate_endpoint_problem

# measurement outputs live outside the package, under experiments/
OUT = Path(__file__).resolve().parents[3] / "experiments/endpoint_tree"

C_DIAG, C_OFF = "#1f3a6e", "#7d9cc9"
C_ROOT, C_COUP = "#2d6b3c", "#d78f6c"
C_FILL = "#c1272d"
CMAP = ListedColormap(["white", C_OFF, C_DIAG, C_COUP, C_ROOT, C_FILL])


def cyclic_reduction_order(P):
    """SOCU's elimination order of a P-block chain: level l with
    stride s = 2^l eliminates blocks s-1 + t*2s."""
    order, levels, seen = [], [], set()
    s = 1
    while len(order) < P:
        level = [i for i in range(s - 1, P, 2 * s) if i not in seen]
        order.extend(level)
        seen.update(level)
        levels.append(len(level))
        s *= 2
    return order, levels


def render_figure(K0, shape, layout, out_name, subtitle,
                  compact=False):
    """One 2x2 figure (chain-order row, cyclic-reduction row) for the
    given endpoint layout: ``"grouped"`` (endpoints in a boundary
    group), ``"inplace"`` (each tail's endpoint at its end), or
    ``"none"`` (no separation: the permutation runs over all T stages
    in chronological order, x_0 first)."""
    B, T, n_b, n_r = shape.dims()
    P = T - 1
    n = K0.shape[0]
    N_pre = B * P * n_b
    N_tail = B * T * n_b

    def build_perm(block_order):
        # block_order indexes prefix storage blocks for the separated
        # layouts, chronological stages for layout "none" (storage
        # block of stage t is T-1-t)
        perm = []
        if layout == "grouped":
            for b in range(B):
                base = b * T * n_b
                for k in block_order:
                    perm.extend(range(base + k * n_b,
                                      base + (k + 1) * n_b))
            for b in range(B):
                base = b * T * n_b + P * n_b
                perm.extend(range(base, base + n_b))
        elif layout == "inplace":
            for b in range(B):
                base = b * T * n_b
                for k in list(block_order) + [P]:
                    perm.extend(range(base + k * n_b,
                                      base + (k + 1) * n_b))
        else:
            for b in range(B):
                base = b * T * n_b
                for t in block_order:
                    k = T - 1 - t
                    perm.extend(range(base + k * n_b,
                                      base + (k + 1) * n_b))
        perm.extend(range(B * T * n_b, n))
        return np.asarray(perm)

    def labels(block_order):
        # a tail's own stages are x_T ... x_1 (the shared root is the
        # stage x_0, drawn last); storage prefix block k of tail i is
        # stage T-k, and the endpoint block is stage 1
        if layout == "none":
            stages = [t + 1 for t in block_order]
        else:
            stages = [T - k for k in block_order]
        out = []
        for i in range(B):
            out += [rf"$x_{{{t}}}^{{{i}}}$" for t in stages]
            if layout == "inplace":
                out.append(rf"$x_{{1}}^{{{i}}}$")
        if layout == "grouped":
            out += [rf"$x_{{1}}^{{{i}}}$" for i in range(B)]
        return out + [r"$x_{0}$"]

    n_perm = T if layout == "none" else P
    word = "tails" if layout == "none" else "prefixes"
    cr_order, levels = cyclic_reduction_order(n_perm)
    orderings = [
        (f"chain-order {word}", build_perm(list(range(n_perm))),
         labels(list(range(n_perm)))),
        (f"cyclic-reduction {word}", build_perm(cr_order),
         labels(cr_order)),
    ]
    if layout == "none":
        # cyclic reduction over the REVERSED stage order (leaf-to-root
        # storage, x_1 last): CR position p is stage T-1-p
        rev = [T - 1 - t for t in cr_order]
        orderings.append((r"cyclic-reduction, reversed stages",
                          build_perm(rev), labels(rev)))
    tick_pos = ([k * n_b + (n_b - 1) / 2 for k in range(B * T)]
                + [N_tail + (n_r - 1) / 2])

    if layout == "grouped":
        major = [b * P * n_b - 0.5 for b in range(1, B)]
        major += [N_pre - 0.5, N_tail - 0.5]
        minor = []
    elif layout == "inplace":
        major = [b * T * n_b - 0.5 for b in range(1, B)]
        major += [N_tail - 0.5]
        minor = [b * T * n_b + P * n_b - 0.5 for b in range(B)]
    else:
        major = [b * T * n_b - 0.5 for b in range(1, B)]
        major += [N_tail - 0.5]
        minor = []

    block_id = np.empty(n, dtype=int)
    block_id[:N_tail] = np.arange(N_tail) // n_b
    block_id[N_tail:] = B * T
    on_diag = block_id[:, None] == block_id[None, :]
    in_root = np.arange(n) >= N_tail
    coupling = in_root[:, None] != in_root[None, :]
    root_both = in_root[:, None] & in_root[None, :]

    n_rows = len(orderings)
    if compact:
        fig, axes = plt.subplots(n_rows, 2,
                                 figsize=(6.2, 3.4 * n_rows),
                                 gridspec_kw={"hspace": 0.30,
                                              "wspace": 0.10})
    else:
        fig, axes = plt.subplots(n_rows, 2,
                                 figsize=(7.0, 3.9 * n_rows),
                                 gridspec_kw={"hspace": 0.22,
                                              "wspace": 0.14})
    for row, (row_name, perm, blk_labels) in enumerate(orderings):
        K = K0[np.ix_(perm, perm)]
        L = np.linalg.cholesky(K)
        pat_K = np.abs(K) > 1e-14
        pat_L = np.abs(L) > 1e-14
        fill = pat_L & ~(pat_K | pat_K.T)
        panels = (
            (pat_K, False,
             rf"matrix $K$: nnz $= {int(pat_K.sum())}$"),
            (pat_L, True,
             rf"Cholesky factor $L$: nnz $= {int(pat_L.sum())}$, "
             rf"fill-in $= {int(fill.sum())}$"),
        )
        for col, (M, is_factor, title) in enumerate(panels):
            ax = axes[row, col]
            img = np.zeros((n, n), dtype=int)
            img[M & ~on_diag] = 1
            img[M & on_diag] = 2
            img[M & coupling] = 3
            img[M & root_both] = 4
            if is_factor:
                img[fill] = 5
            ax.imshow(img, cmap=CMAP, vmin=0, vmax=5,
                      interpolation="nearest")
            for k in range(1, B * T):
                v = k * n_b - 0.5
                ax.axvline(v, color="0.88", lw=0.25, zorder=1)
                ax.axhline(v, color="0.88", lw=0.25, zorder=1)
            for v in minor:
                ax.axvline(v, color="0.65", lw=0.45, zorder=2)
                ax.axhline(v, color="0.65", lw=0.45, zorder=2)
            for v in major:
                ax.axvline(v, color="0.45", lw=0.6, zorder=2)
                ax.axhline(v, color="0.45", lw=0.6, zorder=2)
            ax.set_title(title, fontsize=9)
            if col == 0:
                ax.set_ylabel(rf"\textbf{{{row_name}}}", fontsize=10,
                              labelpad=6)
            ax.set_xticks(tick_pos)
            ax.set_xticklabels(blk_labels, fontsize=7)
            ax.set_yticks(tick_pos)
            ax.set_yticklabels(blk_labels, fontsize=7)
            ax.tick_params(length=0)
            for side in ax.spines.values():
                side.set_linewidth(0.6)
        print(f"{layout}, {row_name}: nnz(L) = {int(pat_L.sum())}, "
              f"fill-in = {int(fill.sum())}, root-column factor nnz "
              f"= {int(pat_L[N_tail:, :N_tail].sum())}")
    handles = [
        Patch(facecolor=C_DIAG, label="tail diagonal blocks"),
        Patch(facecolor=C_OFF, label="tail off-diagonal blocks"),
        Patch(facecolor=C_ROOT, label="root block"),
        Patch(facecolor=C_COUP, label="root--tail coupling"),
        Patch(facecolor=C_FILL, label="fill-in"),
    ]
    fig.legend(handles=handles, loc="lower center",
               ncol=3 if compact else 5,
               frameon=False, fontsize=7.5 if compact else 8,
               bbox_to_anchor=(0.5, -0.035 if compact else -0.008))
    if compact:
        fig.tight_layout(rect=(0, 0.03, 1, 1), h_pad=1.6)
    else:
        lvl_txt = "+".join(str(c) for c in levels)
        fig.suptitle(
            subtitle + "\n"
            rf"($B = {B}$ scenarios, $N = {T}$ stages, root "
            rf"$x_0$ last; bottom row: {word} in the GPU "
            rf"cyclic-reduction "
            rf"order, levels of ${lvl_txt}$)",
            fontsize=10)
        fig.tight_layout(rect=(0, 0.035, 1, 0.945), h_pad=2.2)
    (OUT / "figures").mkdir(exist_ok=True)
    out_pdf = OUT / f"figures/{out_name}"
    fig.savefig(out_pdf, bbox_inches="tight", dpi=300)
    plt.close(fig)
    print("saved", out_pdf)


def main():
    shape = EndpointTreeShape(num_tails=2, num_stages=8,
                              tail_block_dim=3, root_dim=3)
    p = generate_endpoint_problem(shape, seed=7)
    A = p.matrix.to_csr_lower(dtype=np.float64)
    K0 = (A + sp.tril(A, k=-1).T).toarray()

    plt.rcParams.update({"text.usetex": True, "font.family": "serif",
                         "font.size": 9, "figure.dpi": 150,
                         "savefig.bbox": "tight"})

    # T = 10 versions demonstrate the non-power-of-two horizon, where
    # cyclic reduction no longer eliminates the last chain position
    # last, so without explicit separation even the reversed stage
    # order leaks root coupling
    shape10 = EndpointTreeShape(num_tails=2, num_stages=10,
                                tail_block_dim=3, root_dim=3)
    p10 = generate_endpoint_problem(shape10, seed=7)
    A10 = p10.matrix.to_csr_lower(dtype=np.float64)
    K10 = (A10 + sp.tril(A10, k=-1).T).toarray()

    # the in-place layout (each tail keeps its endpoint at its end,
    # matching the solver's storage) is the default idea figure; the
    # boundary-group layout remains available via render_figure(...,
    # "grouped", ...) but is not generated
    for K, shp, suffix in ((K0, shape, "_T8"), (K10, shape10, "")):
        render_figure(
            K, shp, "inplace",
            f"endpoint_parallel{suffix}.pdf",
            r"Endpoint ordering: each tail keeps its root-coupled "
            r"last stage at its end", compact=True)
        render_figure(
            K, shp, "none",
            f"endpoint_ordering_noseparation{suffix}.pdf",
            r"No endpoint separation: the root-coupled stage $x_0$ "
            r"stays inside each tail's permutation")


if __name__ == "__main__":
    main()
